- src/components/markdown.tsx
When setting the _isbn_ without `-` (ie. **9781542866507** instead of **978-1542866507**) the yaml formatter take it as a number and the cover image is not set.
> Fix Book cover image - use isbn even when numeric

- CONTRIBUTING.md
Yup, turns out the token needs `user:email` based on:
https://github.com/lumen-notes/lumen/blob/b66c81ca81aa480bfb45f955bcf4a05fa98d9f1d/src/components/github-auth.tsx#L59
> docs: update `CONTRIBUTING.md` to add missing token scopes

- src/components/markdown.tsx
As per the suggestion [here](https://github.com/lumen-notes/lumen/pull/240#issuecomment-1884455933). 
Check icon will go back to copy icon after 2 seconds.
> feat: UI feedback when copy button clicked

- src/components/repo-form.tsx
Fix for #253.
The radio group in `repo-form.tsx` was missing the radio group name. This resulted in only selectExistingRepo function to be called while trying to create a new repo.
Adding the group name `repo-type` fixes the issue.
> Bug fix for create repository

- src/components/command-menu.tsx
- src/components/nav-bar.tsx
- src/hooks/navigate-with-cache.ts
Part of #204 
Now the command menu looks like this 👇 (when nothing is typed):
Although I was gonna add a separator line between "Settings" and the rest but realized the only UI separator we have is for the DropdownMenu. 
I might create a separator component soon. @colebemis Should I make a custom one or install `@radix-ui/react-separator` and use that instead ?
> Feat: Expanding on command-menu

- docs/query-language.md
- src/hooks/search.ts
- src/schema.ts
- src/utils/parse-note.ts
This adds `tasks:$qualifier` and `has:tasks` to the query language.
- closes https://github.com/lumen-notes/lumen/issues/286
> feat: add ability to filter by open tasks

- src/components/markdown.tsx
Closes #309
This pull request addresses the issue of single dollar signs causing rendering problems in markdown content within the `src/components/markdown.tsx` file. The solution implemented involves modifying the `remarkPlugins` array to include configuration options for the `remarkMath` plugin. Specifically, the `singleDollarTextMath` option is set to `false`, which prevents single dollar signs from being interpreted as math expressions. This change ensures that text containing single dollar signs is rendered correctly without being mistakenly formatted as mathematical notation. The modification is made directly in the `remarkPlugins` array where the `remarkMath` plugin is initialized, ensuring that the configuration applies to all instances of markdown rendering within the component. …
> Fix rendering issue with single dollar signs

- public/robots.txt
This pull request introduces a new `robots.txt` file in the `public` directory of the project. The content of this file is designed to disallow all web crawlers from accessing the site, as indicated by the rules specified within the file. The rules are set to apply to all user agents, effectively blocking all bots from indexing or crawling any part of the site. This change is crucial for controlling the site's visibility on the internet and managing how search engines interact with it.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/lumen-notes/lumen?shareId=b0cca3a0-fcf7-4261-b843-342bd4c86abe).
> Add robots.txt to disallow all web crawlers

- src/components/note-editor.tsx
Closes #306
This pull request addresses the issue of an extra newline being created when leaving edit mode with ctrl+enter on Windows in the `lumen-notes/lumen` project. The modification has been made in the `src/components/note-editor.tsx` file. Specifically, the `onKeyDownCapture` event handler has been updated to prevent the default behavior when the Enter key is pressed along with either the Meta key (Command on Mac) or the Ctrl key, which is the common control key on Windows. This change ensures that the form submission behavior tied to the Meta+Enter or Ctrl+Enter key combination is intercepted and prevented, thus avoiding the creation of an extra newline when exiting edit mode. This solution targets the Windows platform specifically, as the issue was not reproducible on Mac, …
> Fix extra newline on ctrl+enter in Windows

- src/components/note-card.tsx
Updates the pin icon in the note card dropdown menu to turn orange when the note is pinned, ensuring visual consistency with the pin icon displayed on the note card itself.
- Adds conditional styling to the `PinFillIcon16` component within the `DropdownMenu.Item` in `src/components/note-card.tsx`. This change applies the same orange color (`var(--orange-11)`) used for the pin icon on the note card when the note is pinned.
- Utilizes the `isPinned` utility function to determine the pin status of a note and conditionally render the styled pin icon accordingly.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/lumen-notes/lumen?shareId=f3522397-b0da-4d87-b836-8ca885d71485).
> Make pin icon in dropdown menu orange when note is pinned

- src/components/command-menu.tsx
- src/components/icons.stories.tsx
- src/components/icons.tsx
- src/components/nav-bar.tsx
- src/components/note-favicon.tsx
- src/panels/daily.tsx
- src/panels/weekly.tsx
Adds a "This week" item to the "Jump to" section of the command menu in `src/components/command-menu.tsx`, enabling users to navigate to the current weekly note.
- **Navigation Enhancement**: Introduces a new `CommandItem` for "This week" in the command menu, utilizing `toWeekString(new Date())` to generate the current week string and `navigate` function for redirection.
- **Calendar Icon Update**: Implements the use of `getISOWeek` from `date-fns` to display the current week number on the calendar icon for the "This week" menu item.
- **Code Integration**: Adds the import statement for `getISOWeek` from `date-fns` to support the week number calculation.
> Add 'This week' item to command menu

- src/components/icons.tsx
- src/components/note-card.tsx
Closes #349
Adds a "Revert changes" option to the note card dropdown menu for reverting edits made to a note in the editor.
- Implements the `revertChanges` function to reset the editor content to the last saved state of the note and clear the "draft" from localStorage.
- Adds a conditional rendering for the "Revert changes" dropdown item, which only appears when the editor state is dirty.
- Utilizes the existing `isDirty` state to determine if the editor content has been modified from the last saved state, enabling the "Revert changes" option accordingly.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/lumen-notes/lumen/issues/349?shareId=38e68fd7-c894-4d4c-b346-33183e75d754).
> Add 'Revert changes' button to note card

- package-lock.json
- package.json
- src/components/command-menu.tsx
- src/components/note-editor.tsx
- src/components/note-favicon.tsx
- src/components/note-list.tsx
- src/utils/emoji.ts
- src/utils/parse-note.ts
Implements the feature to display a single emoji as the favicon if a note title starts with an emoji in `note-favicon.tsx`.
- **Emoji Detection**: Adds a condition to check if the note title starts with a single emoji using the `emoji-regex` package. If a single emoji is detected at the beginning of the note title, it is set as the favicon.
- **Dependency Addition**: Imports `emojiRegex` from the `emoji-regex` package to facilitate the detection of emojis in note titles.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/lumen-notes/lumen?shareId=6cdc0288-3af2-4beb-ba52-aa12ceed5aef).
> Display emoji as favicon for notes starting with an emoji

- src/components/repo-form.tsx
Update the repo picker to make "Select an existing repository" the default option and move it to the top.
* **Default Option**: Initialize the `repoType` state to "existing" instead of "new".
* **Radio Button Order**: Move the "Select an existing repository" option before "Create a new repository".
---
For more details, open the [Copilot Workspace session](https://copilot-workspace-dev.githubnext.com/lumen-notes/lumen?shareId=3051782d-ad31-4b3e-a87a-a291fe33d228).
> Make 'select repo' the top and default option over 'create repo' in the repo picker

- src/components/note-favicon.tsx
Set the `overflow` property to `visible` for the `svg` element displaying the leading emoji in the `NoteFavicon` component.
* Modify `src/components/note-favicon.tsx` to add the `overflow-visible` class to the `svg` element displaying the leading emoji.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace-dev.githubnext.com/lumen-notes/lumen?shareId=4cf28d65-4e27-4de9-aa3b-74d20931e10b).
> Fix the SVG favicon for notes that start with emojis to be overflow visible

- src/components/markdown.tsx
Remove the scaling effect on hover for the book cover in the `BookCover` component.
* Remove the CSS class `hover:[transform:perspective(30rem)_scale(1.05)_rotate3d(0,1,0,-20deg)]` from the `BookCover` component in `src/components/markdown.tsx`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace-dev.githubnext.com/lumen-notes/lumen?shareId=536e7f56-87ca-4343-b466-51720c44a803).
> Don't scale the book cover on hover

- src/components/panels.tsx
Update the `closePanel` function to only remove the specified panel without affecting other panels.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace-dev.githubnext.com/lumen-notes/lumen?shareId=7a306a76-2ae4-4978-a531-6111469587fa).
> Update `closeFile` behavior

- netlify/edge-functions/github-auth.ts
As exposed in #436, when the app tries to do a push action with an email address that is private, the action will fail.
```
[start] git push
onMessage error:GH007: Your push would publish a private email address.
onMessage You can make your email public or disable this protection by visiting:
onMessage https://github.com/settings/emails
GitPushError: One or more branches were not updated: 
- refs/heads/main: push declined due to email privacy restrictions
at gEe (index-03b654cd.js:456:40)
at async Object.vEe [as push] (index-03b654cd.js:456:332)
at async cDe (index-03b654cd.js:501:34563)
at async push (index-03b654cd.js:614:5288)
```
In order to avoid this, it is necessary to check whether user's email visibility is public. According to the response schema of [/users/emails/ …
> Check for email.visibility also when looking for user email.

- netlify/edge-functions/github-auth.ts
This PR makes the app to look for a public email to login, regardless of whether it is primary or not.
> Choose a public email to use the app

- netlify/edge-functions/github-auth.ts
Hello.
I'm writing again regarding the issue of not being able to log in due to the privacy email problem. Today, I faced again the issue with another account of mine.
By checking the "/user/emails" API endpoint with [Github CLI](https://docs.github.com/es/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#making-a-request), I discovered that sometimes the "visibility" field is null. With this PR, I propose that the app should look for the first email that is not private, instead of looking for the first public one.
I believe this PR will finally resolve issue #436.
Thank you for considering this improvement.
> Check now if email is not private instead

- src/styles/index.css
> [fix] prevent external link and arrow from wrapping separately

- src/components/command-menu.tsx
Tackles #447 
I left some comments on the other possible actions I couldn't connect.
- I had to use tanstack match to get the note id from the url because the Route from `"../routes/_appRoot.notes_.$"` throws an error when I'm in the home page.
- for the share note action, we'll either need a copy of `ShareDialog` inside `command-menu.tsx` or we have global state for that dialog and this way we can open it from the command menu.
- for the attach file action, it needs the `editorRef` and I'm not sure how to obtain it without props drilling 
https://github.com/user-attachments/assets/3f7a670a-1ead-4e77-b389-e2a032b4bb14
> [feat] note actions on command tool

- docs/query-language.md
- src/components/new-note-button.tsx
- src/components/note-list.tsx
- src/hooks/search.ts
- src/utils/search.test.ts
- src/utils/search.ts
- Add support for a `sort:` qualifier in search queries
- Parse and apply the sort qualifier when executing searches
- Ensure search results are ordered according to the specified sort criterion
> Implement sort qualifier for search
