lumen-notes/lumen

README.md, package-lock.json, package.json, src/components/command-menu.tsx, src/components/note-form.tsx, src/components/note-list.tsx, src/components/search-notes.tsx, src/index.tsx, src/panels/date.tsx, src/panels/note.tsx, src/panels/notes.tsx, src/panels/tag.tsx, src/panels/tags.tsx, src/pull-notes.worker.ts, src/utils/file-system.ts, src/utils/parse-note-body.ts
=> Implement query language

package-lock.json, package.json, vite.config.ts
=> Update vite 4

package-lock.json, package.json, src/components/markdown.stories.tsx, src/components/markdown.tsx, src/components/note-editor.tsx
By request of @lostintangent, Lumen now supports emoji 🎉 🔥 🥳
=> Add emoji support

CONTRIBUTING.md, package-lock.json, package.json, src/components/github-auth.tsx
Just to avoid sharing/using the `GITHUB_CLIENT_SECRET` while dev
=> Use personal token dev

src/components/note-editor.tsx
=> add spellcheck and autocorrect

src/components/note-editor.tsx
https://github.com/lumen-notes/lumen/assets/4608155/f68617a0-9917-48af-be07-e33db0bc2758
Closes https://github.com/lumen-notes/lumen/issues/173
=> Autocomplete tags when using the `tags` property

src/components/command-menu.tsx, src/components/note-editor.tsx
The file is not being committed on note creation
=> Fix - use githubupsert when creating note

src/components/note-editor.tsx, src/index.css
https://github.com/lumen-notes/lumen/assets/4608155/1d6af1e4-ac81-4a38-a6da-bde25e9ed4a3
Closes https://github.com/lumen-notes/lumen/issues/155
=> Implement frontmatter autocomplete

docs/metadata.md
=> Fixes typo

src/components/note-list.tsx
=> Closes #187

package-lock.json, package.json, src/components/command-menu.tsx, src/components/fullscreen-container.tsx, src/components/fullscreen.tsx, src/components/link-context.tsx, src/components/link.tsx, src/components/markdown.tsx, src/components/nav-bar.tsx, src/components/note-card.tsx, src/components/note-list.tsx, src/components/panel.tsx, src/components/panels.tsx, src/components/root-layout.tsx, src/components/tag-link.tsx, src/pages/tag.tsx, src/panels/date.tsx, src/panels/file.tsx, src/panels/tag.tsx, src/panels/tags.tsx, src/utils/prev-path-params.ts, src/utils/use-search-param.ts
Minimize re-renders with strategic memoization and mindful use of `useEffect`
=> Performance optimizations

package-lock.json, package.json, src/components/note-card-form.tsx, src/components/note-editor.tsx, src/global-state.ts, src/pages/settings.tsx, src/styles/codemirror.css, src/utils/prev-path-params.ts, src/utils/vim-mode.ts
Closes #176 
Still using the default keymaps from [`@replit/codemirror-vim`](https://github.com/replit/codemirror-vim).
=> feat(editor): vim mode

src/components/icons.tsx, src/components/note-list.tsx, src/components/panel.tsx, src/components/search-input.tsx
=> feat: random notes

netlify/edge-functions/github-auth.ts, src/components/github-auth.tsx
This is related to #211, but not entirely fixing it. 
Those errors are also what led me to open PR #205 previously.
=> fix: addd error handling on get user's emails

src/components/fullscreen.tsx
Disable closing fullscreen dialog on overlay click
=> Disable closing fullscreen dialog on overlay click

package-lock.json
=> Fixing vulnerabilities on Windows

src/components/note-list.tsx, src/components/pill-button.stories.tsx, src/components/pill-button.tsx
I added `removable` prop which will conditionally show the x button inside the `PillButton` and a `onRemove` prop to be triggered when the x icon is clicked
=> feat(ui): removable PillButtons

src/panels/daily.tsx, src/panels/note.tsx, src/utils/date.test.ts, src/utils/date.ts
Add unit tests for date utils
This PR was created with Copilot Workspace (v0.11). For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/lumen-notes/lumen?shareId=3bea85fb-dd99-470b-8a01-2d560f48b7e7).
=> Add unit tests for date utils

package-lock.json
Vulnerabilities before:
```
19 vulnerabilities (8 moderate, 10 high, 1 critical)
```
After
```
12 vulnerabilities (8 moderate, 3 high, 1 critical)
```
I simply ran `npm audit fix`
=> fix: resolve some vulnerabilities

src/components/note-editor.tsx, src/styles/codemirror.css, src/utils/indented-line-wrap.ts
=> Respect indent for wrapped lines

src/components/markdown.tsx, src/styles/markdown.css
=> Proxy external images

src/components/app-header.tsx, src/components/new-note-button.tsx, src/components/sidebar.tsx, src/routes/_appRoot.notes_.$.tsx
Closes #248 
- Added useLocation and useSaveNote hooks to Sidebar component.
- Extracted tag from the URL path and tag qualifiers from the search query.
- Implemented logic to create a note with tags when the note creation button is clicked.
https://github.com/user-attachments/assets/434be2f4-7ba8-4619-93f3-fc6d55c3fe55
=> [feat] sidebar new note button adds tags from query
